[package]
name = "h2c-rust-ref"
version = "6.0.0"
authors = ["armfazh <armfazh@cloudflare.com>"]
edition = "2018"
description = "hash to curve reference implementation"
keywords = ["elliptic curve", "math", "crypto", "ecc", "elliptic", "hash to curve"]
categories = ["cryptography"]
readme = "readme.md"
license = "BSD-3-Clause"

[[bench]]
name = "h2c"
harness = false

[dependencies]
num-bigint = "0.2.6"
sha2 = "0.8.1"
digest = "0.8.1"
lazy_static = "1.4.0"
redox-ecc = { git = "https://github.com/capito27/redox-ecc" }

[dev-dependencies]
criterion = "0.3"
libtest-mimic = "0.2.0"
serde = "1.0.104"
serde_json = "1.0.48"
serde_derive = "1.0.104"
